server:
  port: 7000
spring:
  application:
    name: scw-User
  #MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat  #开启数据库连接池的监控
  #Redis
  redis:
    host: 192.168.188.192
    port: 6379
    password: root

#Mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/offcn/user/mapper/*.xml

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
#logging
logging:
  file:
    path: D:\\log\\scw-user   #日志保存的路径
  level:
    com:
      offcn: debug      #error  debug  info
#短信的配置信息
sms:
  appcode: b69726266414476da2157fc0cdb62c48
  tpl_id: TP1711063
  host: http://dingxin.market.alicloudapi.com
  path: /dx/sendSms
  method: POST